### ISSUE TITLE
Investigate npm issues with running Cypress tests for Playbooks plugin

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-gitpod-config#16]
just for reference I had to `npm install -f` in the playbooks webapp folder to get around an `fsevents` error, and then change the SSH resolution url to https for `mocha-junit-reporter` in the cypress folder

_Issue created from a [Mattermost message](https://community.mattermost.com/_redirect/pl/bb1ex8azspbujmqdqhjxa1g1yr) *by @Phrynobatrachus*._

**Comment by Phrynobatrachus** [comment]
My bad for not copying the exact errors. 

`fsevents`: https://stackoverflow.com/questions/66093284/unsupported-platform-for-fsevents2-3-2-installation-issue

The latter was `publickey denied`, stemming from `tests-e2e/package-lock.json`:

`"resolved": "git+ssh://git@github.com/Phrynobatrachus/mocha-junit-reporter.git#9c2eccdd4d5e78f141887f3d4bd3a9a2124688bd",`

Perhaps I should update that.

**Comment by simcard0000** [comment]
Just for posterity, I've been using [mattermost-gitpod-config](https://github.com/mattermost/mattermost-gitpod-config) and haven't run into this problem on Gitpod yet.
